# .github/workflows/test.yml
name: Test Workflow

on:
  workflow_dispatch:

jobs:
  test-job:
    runs-on: ubuntu-latest

    steps:
      - name: Do nothing
        run: echo "This is a test workflow. Nothing happens here."
