name: Deploy Spring Boot App to EC2 or ECR

on:
  workflow_dispatch:
    inputs:
      target:
        description: 'Deployment Target (ec2 or ecr)'
        required: true
        default: 'ec2'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build JAR
        run: ./gradlew clean bootJar -x test

      - name: Build Docker Image
        run: docker build -t ocpi_images .

      - name: Get Current Version
        id: version
        run: |
          VERSION=$(git describe --tags --abbrev=0 2>/dev/null || echo "v1.0.0")
          MAJOR=$(echo "$VERSION" | cut -d'.' -f1 | sed 's/v//')
          MINOR=$(echo "$VERSION" | cut -d'.' -f2)
          PATCH=$(echo "$VERSION" | cut -d'.' -f3)
          PATCH=$((PATCH + 1))
          NEW_VERSION="v$MAJOR.$MINOR.$PATCH"
          echo "NEW_VERSION=$NEW_VERSION" >> $GITHUB_OUTPUT

      - name: Create Git Tag
        run: git tag ${{ steps.version.outputs.NEW_VERSION }}

      - name: Tag Docker Image for ECR
        if: inputs.target == 'ecr'
        run: |
          docker tag ocpi_images:latest 148761650284.dkr.ecr.ap-south-1.amazonaws.com/ocpi_images:${{ steps.version.outputs.NEW_VERSION }}
          docker tag ocpi_images:latest 148761650284.dkr.ecr.ap-south-1.amazonaws.com/ocpi_images:latest

      - name: Configure AWS CLI
        if: inputs.target == 'ecr'
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      - name: Login to Amazon ECR
        if: inputs.target == 'ecr'
        run: |
          aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 148761650284.dkr.ecr.ap-south-1.amazonaws.com

      - name: Push Image to ECR
        if: inputs.target == 'ecr'
        run: |
          docker push 148761650284.dkr.ecr.ap-south-1.amazonaws.com/ocpi_images:${{ steps.version.outputs.NEW_VERSION }}
          docker push 148761650284.dkr.ecr.ap-south-1.amazonaws.com/ocpi_images:latest

      - name: Push Git Tag
        if: inputs.target == 'ecr'
        run: git push origin ${{ steps.version.outputs.NEW_VERSION }}

      - name: Save Docker Image for EC2
        if: inputs.target == 'ec2'
        run: docker save ocpi_images -o ocpi_images.tar

      - name: Set permissions for Docker image
        if: inputs.target == 'ec2'
        run: chmod 644 ocpi_images.tar

      - name: Transfer Docker Image to EC2
        if: inputs.target == 'ec2'
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_PRIVATE_KEY_TEMP }}
          source: "ocpi_images.tar"
          target: "~/"

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: SSH into EC2 and Deploy from ECR
        if: inputs.target == 'ecr'
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_PRIVATE_KEY_TEMP }}
          script: |
            aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 148761650284.dkr.ecr.ap-south-1.amazonaws.com
            docker stop emsp || true && docker rm emsp || true
            docker stop cpo || true && docker rm cpo || true
            
            docker pull 148761650284.dkr.ecr.ap-south-1.amazonaws.com/ocpi_images:latest
            
            docker run -d --name emsp -p 9443:9443 --restart always \
              -e "SPRING_PROFILES_ACTIVE=emsp" \
              -e "SCHEMA=emsp" \
              -e "SERVER_PORT=9443" \
              -e "SAAS_URL=https://localhost:9443/hooks" \
              -e "PUBLIC_URL=https://localhost:9443" \
              148761650284.dkr.ecr.ap-south-1.amazonaws.com/ocpi_images:latest
            docker run -d --name cpo -p 8443:8443 --restart always \
              -e "SPRING_PROFILES_ACTIVE=cpo" \
              -e "SCHEMA=cpo" \
              -e "SERVER_PORT=8443" \
              -e "SAAS_URL=https://localhost:8443/hooks" \
              -e "PUBLIC_URL=https://localhost:8443" \
              148761650284.dkr.ecr.ap-south-1.amazonaws.com/ocpi_images:latest
      - name: SSH into EC2 and Deploy from Local Image
        if: inputs.target == 'ec2'
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_PRIVATE_KEY_TEMP }}
          script: |
            docker load -i ~/ocpi_images.tar
            docker stop emsp || true && docker rm emsp || true
            docker stop cpo || true && docker rm cpo || true
            docker run -d --name emsp -p 9443:9443 --restart always \
              -e "SPRING_PROFILES_ACTIVE=emsp" \
              -e "SCHEMA=emsp" \
              -e "SERVER_PORT=9443" \
              -e "SAAS_URL=https://localhost:9443/hooks" \
              -e "PUBLIC_URL=https://localhost:9443" \
              ocpi_images:latest
            docker run -d --name cpo -p 8443:8443 --restart always \
              -e "SPRING_PROFILES_ACTIVE=cpo" \
              -e "SCHEMA=cpo" \
              -e "SERVER_PORT=8443" \
              -e "SAAS_URL=https://localhost:8443/hooks" \
              -e "PUBLIC_URL=https://localhost:8443" \
              ocpi_images:latest