name: CI/CD Deployment

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Grant Execute Permissions for Gradle
        run: chmod +x gradlew

      - name: Build CPO WAR
        run: ./gradlew clean bootWar -Pspring.profiles.active=cpo

      - name: Rename and Store CPO WAR
        run: mv build/libs/*.war build/libs/cpo.war

      - name: Build EMSP WAR
        run: ./gradlew clean bootWar -Pspring.profiles.active=emsp

      - name: Rename and Store EMSP WAR
        run: mv build/libs/*.war build/libs/emsp.war

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: spring-boot-apps
          path: build/libs/*.war

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with:
          name: spring-boot-apps
          path: build/libs/

      - name: Add Host to Known Hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H ec2-3-111-29-194.ap-south-1.compute.amazonaws.com >> ~/.ssh/known_hosts

      - name: Deploy to AWS EC2
        env:
          PRIVATE_KEY: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
          HOST: ec2-3-111-29-194.ap-south-1.compute.amazonaws.com
          USER: ec2-user
        run: |
          echo "$PRIVATE_KEY" > private_key.pem
          chmod 600 private_key.pem

          # Upload both WAR files to Tomcat webapps directory
          scp -o StrictHostKeyChecking=no -i private_key.pem build/libs/cpo.war $USER@$HOST:/home/ec2-user/tomcat/webapps/cpo.war
          scp -o StrictHostKeyChecking=no -i private_key.pem build/libs/emsp.war $USER@$HOST:/home/ec2-user/tomcat/webapps/emsp.war

          # Restart Tomcat to load the new WAR files
          ssh -o StrictHostKeyChecking=no -i private_key.pem $USER@$HOST <<EOF
            sudo systemctl restart tomcat
          EOF
