name: CI/CD Deployment

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Grant Execute Permissions for Gradle
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew clean bootWar

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: spring-boot-app
          path: build/libs/*.war

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: spring-boot-app
          path: build/libs/

      - name: Add Host to Known Hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H ec2-3-111-29-194.ap-south-1.compute.amazonaws.com >> ~/.ssh/known_hosts

      - name: Deploy to AWS EC2
        env:
          PRIVATE_KEY: -----BEGIN RSA PRIVATE KEY-----
MIIEpAIBAAKCAQEA4Re44y5H54ITKXqCfmRJfH0TZQKXfS55bgZEIH1bd8AVoc5t
QF+PFK7HtNa35eDQVZG3MD6BbqBQrORhX8sccCk3wNaFb2cfnQL7o89iHRJr4fiN
rc1BSkxOOV0G7sFCjf6Fa5ZDWskeZpTSAyjBXjlh/A8YOC/oGf4FuMBXCRO8XpdT
HtI72udhAXV0pqyvkTVU0bfcZ812dqDYnz/O3uHXiwXrr/FdiqvyaZm5+250sq2U
Jm4yh5cWoeUUXVeDhIP9rC3oMVJdzRS0FkwjUXqmUoU3aCt40IU8kjl1+S9Os7M0
w7xsmNlrVIrL7o3A3uNLuDAUSSS0VM1egs28SQIDAQABAoIBAGYI5tq0xAuBv0Xy
Lu00cMtptzz2q80nIAxr8r33lVr3S9cJSCUCLE3n3Mdw/fPKsSXY4/2OmAWZznhR
HoLaA44kYQ2dMOeLC52VGJTtEUC0dQr+LNs4S/xuEpeWP+pC2PSdB8X5W5bvzEQb
+gdMljssL+qevQ/bR49gwx84sTt/SR2Np5GAyBI+D/SYyGrnLSxQXoGaNUrnwUsn
kqrQZ7a4Y4djpwaKWlsQE7OH+pmTN6lL90OtDDoYqy1h88GBsXfawVvrtxq70Cv6
3FM8EFntzuW60PJ9S8Bd4lLCPfdj9kJq2tKQZu3hFgPXUckCxPa0kYJZWnwy2JSg
0jvBaAECgYEA9F/hezkFwwitzpaU0NmVjw2EwLInLuxveUUFo7HZaQSfHNrjA+zd
dYkukb1VACiaaVnK6ZdabEgExcsTqxzOgp9W8jtt6uVc/u8+mDQDSVYWPZjZC6rd
WyB183XhRQgeNZPIzXJ6rYOHu4WAwUqepnZeH1kCsQkjSVH43Xfwj8ECgYEA680E
Ube+zwlA02/wJF9hKleo5vgpPwi/z1M9igt2/XQ7Zwi6caclaKGcaQSLv223Luoj
6TEczlsau4Ci3lAaQ5Q9wGnHKtfpSAzKjyoCx6lw8tiKtojBXETQJmUjRnh6a7EF
El+9i6usB8y342l4V01PpDHcT1BMPj2WXdhETokCgYArxMiD43Cuv+0xZTL+PRpW
ZttyD/aIpvxIQh6CdSY1cwh0iJfEajY4CPv4Smrg/mS5ncWEFQGzBysjqf251gz+
xD80X4SOX8pKNtuFMzurdOnC2o91UYMYATZfBqv0S0Ht4qxCb9CdJ0O2SHEJLa5A
rk6pWq3qu3JAfZgPQp4pgQKBgQDACeJgoyLU/pY7HMkY9kzt7SJzqNv+qCN+uC5A
RQINfSH70dH2SchfpG774GXn63Tq0mmYuxTYwr3MwwDhyZ76Nrrr/7njHKCyuygk
3HQTI94HCXA/JLVFbg2Pl4LZG7moBy04P5zhKVkbqRCCNx15DE+2S50/Qwg1EHdr
ynwm8QKBgQDwaDwkh+ahOwyBkmez4E3v+9Z06qZxTg1uvTDm8RsWDDSJOylmZfu6
GWnCNvLXYR4Rxl0CiRBJsgKGklxgmllMvx7sOqH8gIWvUydtaSs19UszgvpF7nMs
d8erKhyTjfW5oLSGGp4yGOmAnx7+UEXXRqLN+gZrAZ7rHtJhSPXnzQ==
-----END RSA PRIVATE KEY-----
          HOST: ec2-3-111-29-194.ap-south-1.compute.amazonaws.com
          USER: ec2-user
        run: |
          echo "$PRIVATE_KEY" > private_key.pem
          chmod 600 private_key.pem

          scp -o StrictHostKeyChecking=no -i private_key.pem build/libs/*.war $USER@$HOST:/home/ec2-user/tomcat/webapps/app.war

          ssh -o StrictHostKeyChecking=no -i private_key.pem $USER@$HOST <<EOF
            sudo systemctl restart tomcat
          EOF
