name: CI/CD Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy_cpo:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Grant Execute Permissions for Gradle
        run: chmod +x gradlew

      # Build CPO WAR
      - name: Build CPO with Gradle
        run: ./gradlew clean bootWar -Pspring.profiles.active=cpo 

      - name: Upload CPO Artifact
        uses: actions/upload-artifact@v4
        with:
          name: cpo-war
          path: build/libs/*.war

  deploy_emsp:
    needs: deploy_cpo
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Grant Execute Permissions for Gradle
        run: chmod +x gradlew

      # Build EMSP WAR
      - name: Build EMSP with Gradle
        run: ./gradlew clean bootWar -Pspring.profiles.active=emsp 

      - name: Upload EMSP Artifact
        uses: actions/upload-artifact@v4
        with:
          name: emsp-war
          path: build/libs/*.war

  deploy_to_ec2:
    needs: [deploy_cpo, deploy_emsp]
    runs-on: ubuntu-latest

    steps:
      - name: Add Host to Known Hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H ec2-3-111-29-194.ap-south-1.compute.amazonaws.com >> ~/.ssh/known_hosts

      - name: Download CPO Artifact
        uses: actions/download-artifact@v4
        with:
          name: cpo-war
          path: build/libs/

      - name: Download EMSP Artifact
        uses: actions/download-artifact@v4
        with:
          name: emsp-war
          path: build/libs/

      - name: Deploy to AWS EC2
        env:
          PRIVATE_KEY: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
          HOST: ec2-3-111-29-194.ap-south-1.compute.amazonaws.com
          USER: ec2-user
        run: |
          echo "$PRIVATE_KEY" > private_key.pem
          chmod 600 private_key.pem

          # Upload CPO WAR
          scp -o StrictHostKeyChecking=no -i private_key.pem build/libs/*.war $USER@$HOST:/home/ec2-user/tomcat/webapps/cpo.war

          # Upload EMSP WAR
          scp -o StrictHostKeyChecking=no -i private_key.pem build/libs/*.war $USER@$HOST:/home/ec2-user/tomcat/webapps/emsp.war

          # Restart Tomcat
          ssh -o StrictHostKeyChecking=no -i private_key.pem $USER@$HOST <<EOF
            sudo systemctl restart tomcat
          EOF
